version: '3.7'
services:

  symfony:
    container_name: graphql_symfony
    build:
      context: .docker/symfony
      args:
        TIMEZONE: 'Europe/Paris'
        GIT_USER_EMAIL: 'loic@devlt.fr'
        GIT_USER_NAME: 'Loic Trancon'
    volumes:
      - ./:/var/www/symfony
    networks:
      - symfony

  nginx:
    container_name: graphql_nginx
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www/symfony
    env_file:
      - .docker/.env.nginx
    ports:
      - 8013:80
    networks:
      - symfony

  ###> doctrine/doctrine-bundle ###
  database:
    container_name: graphql_database
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: graphql
      POSTGRES_PASSWORD: password
      POSTGRES_USER: graphql
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 5435:5432
    networks:
      - symfony
  ###< doctrine/doctrine-bundle ###

networks:
  symfony: